server:
  port: 8000
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

auth:
  secret-key: ${AUTH_SECRET_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  client-id: ${CLIENT_ID}
